unset(proj)
unset(bin)
unset(sbin)
unset(libexec)
unset(lib)
unset(dataroot)
unset(sysconf)
unset(sharedstate)
unset(localstate)
unset(include)
unset(doc)
unset(info)
unset(lisp)
unset(locale)
unset(man)
unset(cmakefind)
unset(cmakeexport)
unset(pkgconfig)


set(proj "${PROJECT_NAME}")
set(bin "bin")
set(sbin "sbin")
set(libexec "libexec")
set(lib "lib")
set(dataroot "share")
set(sysconf "etc")
set(sharedstate "com")
set(localstate "var")
set(include "include")
set(doc "${dataroot}/doc/${proj}")
set(info "${dataroot}/info")
set(lisp "${dataroot}/emacs/lisp-site")
set(locale "${dataroot}/locale")
set(man "${dataroot}/man")
set(cmakefind "${dataroot}/${proj}/cmake")
set(cmakeexport "${lib}/${proj}/cmake")
set(pkgconfig "${lib}/pkgconfig")
